# Generated by Django 3.1.7 on 2021-04-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateTimeField(default='2020-05-05'),
            preserve_default=False,
        ),
    ]
