# Generated by Django 3.1.7 on 2021-03-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=100)),
                ('pemail', models.EmailField(max_length=100)),
                ('ppass', models.CharField(max_length=100)),
            ],
        ),
    ]
