# Generated by Django 3.1.7 on 2021-03-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_patient_pcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pcomment',
        ),
    ]
